autoInstallPeers: false

blockExoticSubdeps: true

overrides:
  vite-plus>oxfmt: '-'

peerDependencyRules:
  allowAny:
    - vitest

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

updateConfig:
  ignoreDependencies:
    - '@types/node'
