autoInstallPeers: false

minimumReleaseAgeExclude:
  - '@standard-config/*'

overrides:
  vite-plus>oxfmt: '-'

peerDependencyRules:
  allowAny:
    - '@vitest/coverage-v8'
    - vitest

strictPeerDependencies: true

trustPolicy: no-downgrade
