autoDedupe: true

autoInstallPeers: false

color: always

engineStrict: true

gitChecks: false

lockfile:
  includeResolutionSettings: true

minimumReleaseAgeExclude:
  - '@standard-config/*'

overrides:
  vite-plus>oxfmt: '-'
  vite-plus>oxlint: latest
  vite-plus>oxlint-tsgolint: latest
  vite: npm:@voidzero-dev/vite-plus-core@1.1.0

peerDependencyRules:
  allowAny:
    - typescript
  ignoreMissing:
    - eslint
    - vitest

strictPeerDependencies: true

trustPolicy: no-downgrade
